controller_frequency: 10.0
TrajectoryPlannerROS:
  max_vel_x: 0.10
  min_vel_x: 0.01
  max_rotational_vel: 0.7
  min_in_place_rotational_vel: 0.1
  acc_lim_th: 0.1
  acc_lim_x: 0.05
  acc_lim_y: 0.05

  holonomic_robot: false
  yaw_goal_tolerance: 0.28
  xy_goal_tolerance: 0.15
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

